name: test-workflow

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: git log
      id: gitlog
      run: git log

    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
